---
- name: Install mysql
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - python-mysqldb
    - mysql-server
  notify:
    - restart mysql

- name: Set mysql root password
  mysql_user:
    login_user: root
    name: root
    password: "{{ mysql.root_password }}"
    state: present

- name: Set wordpress database
  mysql_db:
    login_user: root
    login_password: "{{ mysql.root_password }}"
    name: "{{ mysql.wp_database }}"
    encoding: utf8
    state: present

- name: Set wordpress user
  mysql_user:
    login_user: root
    login_password: "{{ mysql.root_password }}"
    name: "{{ mysql.wp_username }}"
    password: "{{ mysql.wp_password }}"
    priv: "*.*:ALL"
    state: present
