---
- name: Install nginx
  become: yes
  become_method: sudo
  apt: name=nginx state=installed

- name: Configure nginx
  become: yes
  become_method: sudo
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ wordpress.application }}"

- name: refect the configuration
  become: yes
  become_method: sudo
  command: "ln -s /etc/nginx/sites-available/{{ wordpress.application }} /etc/nginx/sites-enabled/"
  ignore_errors: True
  notify:
    - restart nginx

- name: Remove /etc/nginx/sites-enabled/default
  become: yes
  become_method: sudo
  command: "rm /etc/nginx/sites-enabled/default"
  ignore_errors: True
  notify:
    -restart nginx
